### Padding and stride

In [98]:
import torch
import numpy as np
import torch.nn as nn

x = torch.rand(size=(8, 8))
print("origin shape: ", x.shape)
print("val: ", x)

# torch.nn.functional.conv2d(input, kernel_size=3, stride=1, padding=1)

origin shape:  torch.Size([8, 8])
val:  tensor([[0.2193, 0.2986, 0.7369, 0.4558, 0.3182, 0.0898, 0.6697, 0.8750],
        [0.4193, 0.0449, 0.4611, 0.5393, 0.4810, 0.9562, 0.6900, 0.7516],
        [0.7703, 0.8017, 0.0812, 0.7176, 0.5509, 0.8178, 0.9061, 0.8752],
        [0.9974, 0.9965, 0.7936, 0.6669, 0.9015, 0.2794, 0.3011, 0.9082],
        [0.4097, 0.9661, 0.3289, 0.0406, 0.7023, 0.9485, 0.9419, 0.4979],
        [0.1865, 0.1421, 0.1349, 0.4432, 0.0478, 0.8625, 0.3974, 0.3051],
        [0.9248, 0.9113, 0.0279, 0.9343, 0.3375, 0.9359, 0.9647, 0.7873],
        [0.4773, 0.8177, 0.5523, 0.5237, 0.2553, 0.0708, 0.4847, 0.5209]])


In [296]:
conv2d = nn.LazyConv2d(out_channels=1, kernel_size=(3, 3), stride=1, padding=1)

/Users/catcolia/anaconda3/envs/NN/lib/python3.11/site-packages/torch/nn/modules/lazy.py:180: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [314]:
def comp_conv2d(
    conv2d: torch.nn.modules.conv.LazyConv2d, x: torch.Tensor, batch_size=1, channel=1
) -> torch.nn.modules.conv.LazyConv2d:
    # batch size, channel -> (batch_size, channel, height, width)
    print("shape: ", (batch_size, channel) + x.shape)
    x = x.reshape((batch_size, channel) + x.shape)
    print("x: ", x)
    y = conv2d(x)
    return y


conv2d.forward(torch.ones_like(torch.empty(1, 1, 8, 8)))
conv2d.weight = nn.Parameter(torch.ones_like(conv2d.weight))
print(conv2d.weight)

conv2d_res = comp_conv2d(conv2d, x)
conv2d.weight = nn.Parameter(torch.ones_like(conv2d.weight))
print("conv2d bias:", conv2d.bias)
print("conv2d weight:", conv2d.weight)
print("conv2d shape:", conv2d_res.shape)

print(conv2d_res)

Parameter containing:
tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]], requires_grad=True)
shape:  (1, 1, 8, 8)
x:  tensor([[[[0.2193, 0.2986, 0.7369, 0.4558, 0.3182, 0.0898, 0.6697, 0.8750],
          [0.4193, 0.0449, 0.4611, 0.5393, 0.4810, 0.9562, 0.6900, 0.7516],
          [0.7703, 0.8017, 0.0812, 0.7176, 0.5509, 0.8178, 0.9061, 0.8752],
          [0.9974, 0.9965, 0.7936, 0.6669, 0.9015, 0.2794, 0.3011, 0.9082],
          [0.4097, 0.9661, 0.3289, 0.0406, 0.7023, 0.9485, 0.9419, 0.4979],
          [0.1865, 0.1421, 0.1349, 0.4432, 0.0478, 0.8625, 0.3974, 0.3051],
          [0.9248, 0.9113, 0.0279, 0.9343, 0.3375, 0.9359, 0.9647, 0.7873],
          [0.4773, 0.8177, 0.5523, 0.5237, 0.2553, 0.0708, 0.4847, 0.5209]]]])
conv2d bias: Parameter containing:
tensor([0.0557], requires_grad=True)
conv2d weight: Parameter containing:
tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]], requires_grad=True)
conv2d shape: torch.Size([1, 1, 8, 8])
tens