In [20]:
import numpy as np

arr = np.array([1,2,3,4,5])
# arr.fill()
print(arr)

arr = np.empty((4,2))

arr[0].fill(1)
print(arr)

np.random.random(size=1)

[1 2 3 4 5]
[[1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


array([0.87479632])

In [3]:
def text():
    global add
    add= "http://c.biancheng.net/java/"
    print("函数体内访问：",add)
text()
print('函数体外访问：',add)

SyntaxError: name 'add' is assigned to before global declaration (268321043.py, line 4)