Shuffle, batch的作用
> https://zhuanlan.zhihu.com/p/42417456
> https://blog.csdn.net/QLBFA/article/details/108143449

**Shuffle: for perfect shuffling, a buffer size greater than or equal to the full size of the dataset is required.**

A `tf.Tensor` represents a multidimensional array of elements.

In [48]:
import tensorflow as tf
import numpy as np

test = tf.data.Dataset.from_tensor_slices(np.array([1, 2, 3, 4, 5, 6]))
batchs = test.shuffle(6).batch(2)
for i in batchs: print(i)

tf.Tensor([5 2], shape=(2,), dtype=int64)
tf.Tensor([6 3], shape=(2,), dtype=int64)
tf.Tensor([1 4], shape=(2,), dtype=int64)


tensorflow.python.framework.tensor.Tensor

Sequential 顺序模型
> https://keras.io/zh/getting-started/sequential-model-guide/

HardMax 求最大值 非黑即白
SoftMax Softmax的含义在于不再唯一的确定某一个最大值，而是为每个输出分类的结果都赋予一个概率值，表示属于每个类别的可能性  
-> a in arr(length:C), softmax(a) = a / SUM_ALL(Exp(v), v in arr)
> https://zhuanlan.zhihu.com/p/105722023  

使用反向传播求解梯度进而使用梯度下降进行参数更新  

> 交叉熵 https://zhuanlan.zhihu.com/p/149186719

In [78]:
# HardMax
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(np.max(arr))

# HardMax
import tensorflow as tf

max = tf.reduce_max([1, 2, 3, 4, 5])
print(max)

# SoftMax 不使用指数
softmax = arr / tf.reduce_sum(arr)
print(softmax)

# SoftMax 使用指数
arr = tf.constant(arr, dtype=tf.float32)
softmax = tf.exp(arr) / tf.reduce_sum(tf.exp(arr))

print(softmax)
print(tf.nn.softmax(arr))

5
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([0.06666667 0.13333333 0.2        0.26666667 0.33333333], shape=(5,), dtype=float64)
tf.Tensor([0.01165623 0.03168492 0.08612854 0.23412165 0.6364086 ], shape=(5,), dtype=float32)
tf.Tensor([0.01165623 0.03168492 0.08612853 0.23412165 0.6364086 ], shape=(5,), dtype=float32)


One hot 编码 -> 分类特征数字化

梯度下降 逻辑回归 支持向量机SVM 交叉熵  
https://zhuanlan.zhihu.com/p/74874291

In [1]:
# Sequential Model
import tensorflow as tf

# Create a `Sequential` model and add a Dense layer as the first layer.
model = tf.keras.models.Sequential()
model.add(tf.keras.Input(shape=(16,)))
model.add(tf.keras.layers.Dense(32, activation='relu'))
# Now the model will take as input arrays of shape (None, 16)
# and output arrays of shape (None, 32).
# Note that after the first layer, you don't need to specify
# the size of the input anymore:
model.add(tf.keras.layers.Dense(32))
model.output_shape
(None, 32)

2023-11-14 10:42:56.746827: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M2 Pro
2023-11-14 10:42:56.746850: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2023-11-14 10:42:56.746855: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2023-11-14 10:42:56.746890: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-11-14 10:42:56.746907: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


(None, 32)

In [6]:
import tensorflow as tf

tensor = tf.constant([[0, 2, 3], [4, 5, 6]], dtype=tf.float32)
print(0.9 * tf.ones_like(tensor))
print(tf.zeros_like(tensor))

tf.Tensor(
[[0.9 0.9 0.9]
 [0.9 0.9 0.9]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [7]:
tf.__version__

'2.14.0'

In [11]:
@tf.function
def add(a, b):
    return a + b


add(tf.constant([1, 2, 4],dtype=tf.float32),
    tf.constant([3, 4, 5],dtype=tf.float32))

type(add)

tensorflow.python.eager.polymorphic_function.polymorphic_function.Function

In [14]:
pic_nums = 16
noise_dim = 100
seed = tf.random.normal((pic_nums,noise_dim))

<tf.Tensor: shape=(5, 100), dtype=float32, numpy=
array([[-1.3544159 ,  0.7045493 ,  0.03666191,  0.86918795,  0.43842277,
        -0.53439844, -0.07710292,  1.5658046 , -0.1012345 , -0.2744975 ,
         1.420466  ,  1.2609465 , -0.4364091 , -1.963399  , -0.06452482,
        -1.056841  ,  1.0019135 ,  0.6735137 ,  0.06987705, -1.4077919 ,
         1.0278524 ,  0.2797411 , -0.01347954,  1.8451811 ,  0.9706112 ,
        -1.0242516 , -0.6544423 , -0.29738778, -1.3240397 ,  0.28785658,
        -0.87579006, -0.08856997,  0.6921164 ,  0.842157  , -0.06378508,
         0.9280078 , -0.6039788 , -0.17669262,  0.04221032,  0.29037958,
        -0.2960446 , -0.21134192,  0.01063002,  1.5165399 ,  0.27305746,
        -0.29925638, -0.36523244,  0.61883324, -1.0130817 ,  0.28291693,
         1.2132235 ,  0.46988976,  0.37944326, -0.66640246,  0.60545963,
         0.19181171,  0.80458266,  0.47690514, -0.7812124 , -0.996891  ,
         0.3314997 , -0.5445253 ,  1.5222509 ,  0.593032  , -0.63509274,
 